version: '3.8'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  vault:
    image: vault:1.13.1
    container_name: wallet_vault
    tty: true
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "http://0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_ADDRESS: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ${PWD}/docker/vault/file:/vault/file
      - ${PWD}/docker/vault/config:/vault/config:rw
    entrypoint: "vault server -config=/vault/config/config.json"


volumes:
  db_data:
  redis_data: